name: poskiorb-dev

channels:
  - conda-forge

dependencies:
  - python =3.8
  - build
  - black
  - flake8
  - interrogate
  - isort
  - pyupgrade
  - sphinx
  - sphinx-rtd-theme
  - sphinx-automodapi
